In [1]:
#3.Ordinal encoding :- used to encode categorial data that have an ordeer or ranking

In [2]:
import pandas as pd 
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df=pd.DataFrame({
    'size': ['small','medium','large','medium','small','large']
})

In [4]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [5]:
# create Instance 
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [6]:
encoded=encoder.fit_transform(df[['size']])

In [7]:
encoded

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [8]:
encoder.transform([['small']])

C:\Users\ayush\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

In [9]:
od=pd.DataFrame(encoded,columns=['Rankings'])
pd.concat([df,od],axis=1)

     size  Rankings
0   small       0.0
1  medium       1.0
2   large       2.0
3  medium       1.0
4   small       0.0
5   large       2.0

In [ ]:
#